apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: payment-api
          image: fabianogoes/payment-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
          envFrom:
            - secretRef:
                name: payment-secret
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: DB_URI
            - name: DB_NAME
              value: "tech_challenge_payment_db"
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: ":8080"
            - name: API_VERSION
              value: "4.0"
      restartPolicy: Always

